source "https://www.rubygems.org"

gem 'cucumber', '>=2.0.0'
gem 'capybara', '2.6.2'
gem 'rspec', '3.4.0'
gem 'rack', '1.6.4'
gem 'selenium-webdriver', '2.53.4'
gem 'parallel_tests', '2.4.0'
gem 'require_all', '1.3.3'
gem 'sauce_whisk', '0.0.21'
gem 'rake', '10.5.0'
gem 'site_prism', '2.8'
